doctrine:
    dbal:
        connections:
            default:
                url: "sqlite:///%kernel.project_dir%/var/application.db"
            bacula:
                url: '%env(resolve:BACULA_DATABASE_URL)%'
                options:
                    PDO::ATTR_CASE: PDO::CASE_LOWER,

        default_connection: default

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/application/Entity/Core'
                        prefix: 'App\Entity\Core'
                        alias: default
                        type: annotation
            bacula:
                connection: bacula
                mappings:
                    Bacula:
                        is_bundle: false
                        dir: '%kernel.project_dir%/application/Entity/Bacula'
                        prefix: 'App\Entity\Bacula'
                        alias: bacula
                        type: annotation

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
