twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_datetime_format: '%app.datetime_format%'
        app_datetime_format_short: '%app.datetime_format_short%'

when@test:
    twig:
        strict_variables: true