#!/usr/bin/env php
<?php

/**
 * Copyright (C) 2018-present Davide Franco
 *
 * This file is part of the Bacula-Web project.
 *
 * Bacula-Web is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Bacula-Web is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Bacula-Web. If not, see
 * <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/vendor/autoload_runtime.php';

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

return function(array $context) {
    $kernel = new Kernel($context['APP_ENV'], $context['APP_DEBUG'] );

    return new Application($kernel);
};
