#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Copyright (C) 2010-2023 Davide Franco
 *
 * This file is part of Bacula-Web.
 *
 * Bacula-Web is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Bacula-Web is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Bacula-Web. If not, see
 * <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/core/bootstrap.php';

use App\Command\CheckCommand;
use App\Command\PublishAssetsCommand;
use App\Command\SetupAuthCommand;
use App\Command\ShowVersionCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->setName($_ENV['APP_NAME'] . ' console');
$application->setVersion($_ENV['APP_VERSION']);

$application->addCommands(
    [
        new ShowVersionCommand(),
        new SetupAuthCommand(),
        new PublishAssetsCommand(),
        new CheckCommand()
    ]
);

$application->run();
