name: Code analysis

on:
  push:
    branches:
      - 'master'
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: php-actions/composer@v6
        with:
          php_extensions: pdo_mysql pdo_sqlite pdo_pgsql gettext openssl pdo sqlite3 posix

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3