name: Composer test

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
      - 'dev-**'
      - 'refactor/**'
      - '**.x'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.version }}"
        extensions: pdo_mysql, pdo_sqlite, pdo_pgsql, gettext, openssl, pdo, sqlite3, mbstring
        tools: composer:v2

    - name: Print PHP version
      run: echo ${{ steps.setup-php.outputs.php-version }}

    - name: Composer install
      run: composer install

    - name: Check for security vulnerability advisories
      run: composer audit --abandoned=report

    - name: Validate composer.json and composer.lock
      run: composer validate --strict