name: Docker image build

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: metadata
        uses: docker/metadata@v5
        with:
          images: baculaweb/bacula-web
          tags: |
            type=semver,pattern={{version}}
              id: meta

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: "docker/Dockerfile"
          no-cache: true
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
